language: c
sudo: required

before_install:
    - sudo apt-get clean && sudo apt-get update
    - sudo apt-get install gcc-4.6 hdf5-tools libmpich1.0-dev libhdf5-mpich-dev

script:
    - pwd
    - cd ED/build/bin
    - make OPT=opt.gfortran